/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as HostRouteImport } from './routes/host'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as HostsIndexRouteImport } from './routes/hosts/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as MeSettingsRouteImport } from './routes/me/settings'
import { Route as MePaymentRouteImport } from './routes/me/payment'
import { Route as MeNotificationsRouteImport } from './routes/me/notifications'
import { Route as MeMyGymRouteImport } from './routes/me/my-gym'
import { Route as MeHelpRouteImport } from './routes/me/help'
import { Route as MeBecomeHostRouteImport } from './routes/me/become-host'
import { Route as HostsMapRouteImport } from './routes/hosts/map'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ClassesClassIdRouteImport } from './routes/classes.$classId'
import { Route as ClassesClassIdPayRouteImport } from './routes/classes.$classId.pay'
import { Route as ClassesClassIdConfirmationRouteImport } from './routes/classes.$classId.confirmation'
import { Route as ClassesClassIdBookRouteImport } from './routes/classes.$classId.book'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSettingsRoute = MeSettingsRouteImport.update({
  id: '/me/settings',
  path: '/me/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MePaymentRoute = MePaymentRouteImport.update({
  id: '/me/payment',
  path: '/me/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MeNotificationsRoute = MeNotificationsRouteImport.update({
  id: '/me/notifications',
  path: '/me/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeMyGymRoute = MeMyGymRouteImport.update({
  id: '/me/my-gym',
  path: '/me/my-gym',
  getParentRoute: () => rootRouteImport,
} as any)
const MeHelpRoute = MeHelpRouteImport.update({
  id: '/me/help',
  path: '/me/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MeBecomeHostRoute = MeBecomeHostRouteImport.update({
  id: '/me/become-host',
  path: '/me/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsMapRoute = HostsMapRouteImport.update({
  id: '/hosts/map',
  path: '/hosts/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HostRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdPayRoute = ClassesClassIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => ClassesClassIdRoute,
} as any)
const ClassesClassIdConfirmationRoute =
  ClassesClassIdConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => ClassesClassIdRoute,
  } as any)
const ClassesClassIdBookRoute = ClassesClassIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ClassesClassIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/browse': typeof BrowseRoute
  '/host': typeof HostRouteWithChildren
  '/mobile': typeof MobileRoute
  '/saved': typeof SavedRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/new': typeof HostNewRoute
  '/hosts/map': typeof HostsMapRoute
  '/me/become-host': typeof MeBecomeHostRoute
  '/me/help': typeof MeHelpRoute
  '/me/my-gym': typeof MeMyGymRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/payment': typeof MePaymentRoute
  '/me/settings': typeof MeSettingsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/hosts/': typeof HostsIndexRoute
  '/me/': typeof MeIndexRoute
  '/classes/$classId/book': typeof ClassesClassIdBookRoute
  '/classes/$classId/confirmation': typeof ClassesClassIdConfirmationRoute
  '/classes/$classId/pay': typeof ClassesClassIdPayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/browse': typeof BrowseRoute
  '/host': typeof HostRouteWithChildren
  '/mobile': typeof MobileRoute
  '/saved': typeof SavedRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/new': typeof HostNewRoute
  '/hosts/map': typeof HostsMapRoute
  '/me/become-host': typeof MeBecomeHostRoute
  '/me/help': typeof MeHelpRoute
  '/me/my-gym': typeof MeMyGymRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/payment': typeof MePaymentRoute
  '/me/settings': typeof MeSettingsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/hosts': typeof HostsIndexRoute
  '/me': typeof MeIndexRoute
  '/classes/$classId/book': typeof ClassesClassIdBookRoute
  '/classes/$classId/confirmation': typeof ClassesClassIdConfirmationRoute
  '/classes/$classId/pay': typeof ClassesClassIdPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/browse': typeof BrowseRoute
  '/host': typeof HostRouteWithChildren
  '/mobile': typeof MobileRoute
  '/saved': typeof SavedRoute
  '/classes/$classId': typeof ClassesClassIdRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/new': typeof HostNewRoute
  '/hosts/map': typeof HostsMapRoute
  '/me/become-host': typeof MeBecomeHostRoute
  '/me/help': typeof MeHelpRoute
  '/me/my-gym': typeof MeMyGymRoute
  '/me/notifications': typeof MeNotificationsRoute
  '/me/payment': typeof MePaymentRoute
  '/me/settings': typeof MeSettingsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/hosts/': typeof HostsIndexRoute
  '/me/': typeof MeIndexRoute
  '/classes/$classId/book': typeof ClassesClassIdBookRoute
  '/classes/$classId/confirmation': typeof ClassesClassIdConfirmationRoute
  '/classes/$classId/pay': typeof ClassesClassIdPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/auth'
    | '/bookings'
    | '/browse'
    | '/host'
    | '/mobile'
    | '/saved'
    | '/classes/$classId'
    | '/events/$eventId'
    | '/host/new'
    | '/hosts/map'
    | '/me/become-host'
    | '/me/help'
    | '/me/my-gym'
    | '/me/notifications'
    | '/me/payment'
    | '/me/settings'
    | '/profile/$userId'
    | '/hosts/'
    | '/me/'
    | '/classes/$classId/book'
    | '/classes/$classId/confirmation'
    | '/classes/$classId/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/bookings'
    | '/browse'
    | '/host'
    | '/mobile'
    | '/saved'
    | '/classes/$classId'
    | '/events/$eventId'
    | '/host/new'
    | '/hosts/map'
    | '/me/become-host'
    | '/me/help'
    | '/me/my-gym'
    | '/me/notifications'
    | '/me/payment'
    | '/me/settings'
    | '/profile/$userId'
    | '/hosts'
    | '/me'
    | '/classes/$classId/book'
    | '/classes/$classId/confirmation'
    | '/classes/$classId/pay'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/auth'
    | '/bookings'
    | '/browse'
    | '/host'
    | '/mobile'
    | '/saved'
    | '/classes/$classId'
    | '/events/$eventId'
    | '/host/new'
    | '/hosts/map'
    | '/me/become-host'
    | '/me/help'
    | '/me/my-gym'
    | '/me/notifications'
    | '/me/payment'
    | '/me/settings'
    | '/profile/$userId'
    | '/hosts/'
    | '/me/'
    | '/classes/$classId/book'
    | '/classes/$classId/confirmation'
    | '/classes/$classId/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  BrowseRoute: typeof BrowseRoute
  HostRoute: typeof HostRouteWithChildren
  MobileRoute: typeof MobileRoute
  SavedRoute: typeof SavedRoute
  ClassesClassIdRoute: typeof ClassesClassIdRouteWithChildren
  EventsEventIdRoute: typeof EventsEventIdRoute
  HostsMapRoute: typeof HostsMapRoute
  MeBecomeHostRoute: typeof MeBecomeHostRoute
  MeHelpRoute: typeof MeHelpRoute
  MeMyGymRoute: typeof MeMyGymRoute
  MeNotificationsRoute: typeof MeNotificationsRoute
  MePaymentRoute: typeof MePaymentRoute
  MeSettingsRoute: typeof MeSettingsRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  HostsIndexRoute: typeof HostsIndexRoute
  MeIndexRoute: typeof MeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/settings': {
      id: '/me/settings'
      path: '/me/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof MeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/payment': {
      id: '/me/payment'
      path: '/me/payment'
      fullPath: '/me/payment'
      preLoaderRoute: typeof MePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/notifications': {
      id: '/me/notifications'
      path: '/me/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof MeNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/my-gym': {
      id: '/me/my-gym'
      path: '/me/my-gym'
      fullPath: '/me/my-gym'
      preLoaderRoute: typeof MeMyGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/help': {
      id: '/me/help'
      path: '/me/help'
      fullPath: '/me/help'
      preLoaderRoute: typeof MeHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/become-host': {
      id: '/me/become-host'
      path: '/me/become-host'
      fullPath: '/me/become-host'
      preLoaderRoute: typeof MeBecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/map': {
      id: '/hosts/map'
      path: '/hosts/map'
      fullPath: '/hosts/map'
      preLoaderRoute: typeof HostsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/new': {
      id: '/host/new'
      path: '/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof HostRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId/pay': {
      id: '/classes/$classId/pay'
      path: '/pay'
      fullPath: '/classes/$classId/pay'
      preLoaderRoute: typeof ClassesClassIdPayRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
    '/classes/$classId/confirmation': {
      id: '/classes/$classId/confirmation'
      path: '/confirmation'
      fullPath: '/classes/$classId/confirmation'
      preLoaderRoute: typeof ClassesClassIdConfirmationRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
    '/classes/$classId/book': {
      id: '/classes/$classId/book'
      path: '/book'
      fullPath: '/classes/$classId/book'
      preLoaderRoute: typeof ClassesClassIdBookRouteImport
      parentRoute: typeof ClassesClassIdRoute
    }
  }
}

interface HostRouteChildren {
  HostNewRoute: typeof HostNewRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostNewRoute: HostNewRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

interface ClassesClassIdRouteChildren {
  ClassesClassIdBookRoute: typeof ClassesClassIdBookRoute
  ClassesClassIdConfirmationRoute: typeof ClassesClassIdConfirmationRoute
  ClassesClassIdPayRoute: typeof ClassesClassIdPayRoute
}

const ClassesClassIdRouteChildren: ClassesClassIdRouteChildren = {
  ClassesClassIdBookRoute: ClassesClassIdBookRoute,
  ClassesClassIdConfirmationRoute: ClassesClassIdConfirmationRoute,
  ClassesClassIdPayRoute: ClassesClassIdPayRoute,
}

const ClassesClassIdRouteWithChildren = ClassesClassIdRoute._addFileChildren(
  ClassesClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  BrowseRoute: BrowseRoute,
  HostRoute: HostRouteWithChildren,
  MobileRoute: MobileRoute,
  SavedRoute: SavedRoute,
  ClassesClassIdRoute: ClassesClassIdRouteWithChildren,
  EventsEventIdRoute: EventsEventIdRoute,
  HostsMapRoute: HostsMapRoute,
  MeBecomeHostRoute: MeBecomeHostRoute,
  MeHelpRoute: MeHelpRoute,
  MeMyGymRoute: MeMyGymRoute,
  MeNotificationsRoute: MeNotificationsRoute,
  MePaymentRoute: MePaymentRoute,
  MeSettingsRoute: MeSettingsRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  HostsIndexRoute: HostsIndexRoute,
  MeIndexRoute: MeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
