/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as HostRouteImport } from './routes/host'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ClassesClassIdRouteImport } from './routes/classes.$classId'

const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HostRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/browse': typeof BrowseRoute
  '/host': typeof HostRouteWithChildren
  '/mobile': typeof MobileRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/new': typeof HostNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/browse': typeof BrowseRoute
  '/host': typeof HostRouteWithChildren
  '/mobile': typeof MobileRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/new': typeof HostNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/browse': typeof BrowseRoute
  '/host': typeof HostRouteWithChildren
  '/mobile': typeof MobileRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/host/new': typeof HostNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/browse'
    | '/host'
    | '/mobile'
    | '/classes/$classId'
    | '/events/$eventId'
    | '/host/new'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/browse'
    | '/host'
    | '/mobile'
    | '/classes/$classId'
    | '/events/$eventId'
    | '/host/new'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/browse'
    | '/host'
    | '/mobile'
    | '/classes/$classId'
    | '/events/$eventId'
    | '/host/new'
    | '/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  BrowseRoute: typeof BrowseRoute
  HostRoute: typeof HostRouteWithChildren
  MobileRoute: typeof MobileRoute
  ClassesClassIdRoute: typeof ClassesClassIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/new': {
      id: '/host/new'
      path: '/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof HostRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HostRouteChildren {
  HostNewRoute: typeof HostNewRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostNewRoute: HostNewRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  BrowseRoute: BrowseRoute,
  HostRoute: HostRouteWithChildren,
  MobileRoute: MobileRoute,
  ClassesClassIdRoute: ClassesClassIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
